templates:
  - './alert.tmpl'
route:
  receiver: 'wechat'

receivers:
  - name: 'wechat'
    wechat_configs:
      - send_resolved: true
        api_secret: ${API_SECRET}
        api_url: ${API_URL}
        corp_id: ${CORP_ID}
        to_user: '@all'
        agent_id: ${AGENT_ID}
